/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {

        readImageFile();


    }

    public static void readImageFile(){
        File f = null;
        BufferedImage image = null;
        //width of the image
        int width = 100;
        //height of the image
        int height = 100;



        //read image file
        try {
            f = new File("/Users/paulacruz/Documents/codefellows/401/java-fundamentals/bitmap-transformer/assets/mario.bmp");
            image = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
            image = ImageIO.read(f);
            System.out.println("Reading complete.");
        }catch(IOException e){
            System.out.println("Error: " +e );
        }
        //write image
        //unchanged new image
        try{
            f = new File("/Users/paulacruz/Documents/codefellows/401/java-fundamentals/bitmap-transformer/assets/marioNew.bmp");
            ImageIO.write(image,"bmp", f);
            System.out.println("Completed Writing");
        }catch(IOException e){
            System.out.println("Error: " +e);
        }


    }

}
